{{- $fullName := include "dev-app.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "dev-app.name" . }}
    helm.sh/chart: {{ include "dev-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: merge
    merge.ingress.kubernetes.io/config: merged-ingress-for-dev-app
spec:
  rules:
    - host: {{ .Values.hostName }}
      https:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          - path: /*
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
