apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-app-downscale
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: dev-app-deployments-scaling
rules:
  - apiGroups: ["extensions"]
    resources: ["deployments/scale"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-app-downscale-deployments-scaling
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-app-deployments-scaling
subjects:
  - kind: ServiceAccount
    name: dev-app-downscale
    namespace: default

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dev-app-downscale
spec:
  schedule: "0 13 * * *" # scaledown at 22:00 UTC+09:00
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dev-app-downscale
          containers:
            - name: kubectl
              image: lachlanevenson/k8s-kubectl:v1.13.4
              args:
              - scale
              - deployment
              - --namespace=default
              - --all
              - --replicas=0
          restartPolicy: Never
